import QtQuick

QtObject {
    readonly property bool isLightTheme: true

    readonly property color primary: "#398BF2"
    readonly property color accent: "#398BF2"
    readonly property color foreground: "#646464"
    readonly property color background: "#FFFFFF"
    readonly property color toolbarTextColor: "#FFFFFF"
    readonly property color toolbarBackground: "#4B98F9"
    readonly property color toolbarShadow: "#548ED7"
    readonly property color searchPlaceholder: "#80FFFFFF"
    readonly property color settingsPlaceholder: "#99646464"
    readonly property color snailButtonInactiveColor: "#E3E3E3"
    readonly property color snailButtonActiveColor: "#F5DB48"
    readonly property color border: "#DDDDDD"
    readonly property color selectedDownloadBackground: "#EFEFEF"
    readonly property color selectModeBarAndPlusBtn: "#398BF2"
    readonly property color actionBtnStart: "#E3F0FF"
    readonly property color actionBtnPause: "#F8F8F8"
    readonly property color actionBtnFolder: "#EAFFFC"
    readonly property color actionBtnRestart: "#FFE0E0"
    readonly property color drawerIcon: "#398BF2"
    readonly property color drawerBackground: "#FFFFFF"
    readonly property color sortCheck: "#398BF2"
    readonly property color link: "#4B98F9"
    readonly property string progressMapClear: Qt.resolvedUrl("../../images/mobile/light/progressmap_clear.svg")
    readonly property string progressMapFill: Qt.resolvedUrl("../../images/mobile/light/progressmap_fill.svg")
    readonly property string progressMapClearBorder: "#d7e8ed"
    readonly property string progressMapFillBorder: "#16a4fa"
    readonly property string progressMapFillBackground: "#8bd0fb"
    readonly property string infiniteActive: Qt.resolvedUrl("../../images/mobile/light/infinite_active.gif")
    readonly property string infiniteInactive: Qt.resolvedUrl("../../images/mobile/light/infinite_inactive.png")
    readonly property color snailMode: "#F5DB48"
    readonly property color highMode: "#5AC981"
    readonly property color mediumMode: "#5C69FF"
    readonly property color lowMode: "#FF5C5C"
    readonly property color errorMode: "#FF5C5C"
    readonly property color sortButton: "#4B98F9"
    readonly property color progressRunning: "#90C1FF"
    readonly property color progressPaused: "#E3E3E3"
    readonly property color progressDone: "#93FFF2"
    readonly property color progressError: "#F86061"
    readonly property color progressBorder: "#707070"
    readonly property color errorMessage: "#F86061"
    readonly property color successMessage: "#5AC981"
    readonly property color warningMessage: "#5C69FF"
    readonly property color previewOverlay: "transparent"
    readonly property color highPriority: "#4B98F9"
    readonly property color lowPriority: "#CECECE"
    readonly property color dimming: "#A6FFFFFF"
    readonly property color switchBackgroundOn: "#7DB2F7"
    readonly property color switchTumblerOn: "#398BF2"
    readonly property color switchBackgroundOff: "#E3E3E3"
    readonly property color switchTumblerOff: "#909090"
    readonly property color generalSettingsBackground: "#e3e3e3"
    readonly property color generalSettingsBorder: "#CACACA"
    readonly property color tapAnimation: "#EFEFEF"
    readonly property color voteDialogGlow: "#BABABA"
//    readonly property color voteDialogBorder: "#BEDAFF"
    readonly property color voteDialogBackground: "#F7F7F7"
    readonly property color voteDialogText: "#646464"
    readonly property color voteDialogYesBtnText: "#398BF2"
    readonly property color voteDialogNoBtnText: "#636363"
    readonly property color voteDialogYesBtnBackground: "#fff"
    readonly property color voteDialogNoBtnBackground: "#fff"
    readonly property color voteDialogYesBtnBorder: "#BEDAFF"
    readonly property color voteDialogNoBtnBorder: "#E6E6E6"
    readonly property color timePickerCurrentItemText: "#4a4a4a"
    readonly property color timePickerText: "#999"
    readonly property color schedulerLabelText: "#4B98F9"
    readonly property color schedulerLabelSelectedText: "#646464"
    readonly property color waitPageClr1: "#eee"

    readonly property url attentionImg: Qt.resolvedUrl("../../images/common/light/attention.svg")
}
